service: gt

frameworkVersion: '>=2.33.0 <3.0.0'

provider:
  name: aws
  runtime: go1.x
  region: us-east-2
  stage: ${opt:stage,'dev'}
  environment:
    # you can define service wide environment variables here
    GIN_MODE: "release"
    memorySize: 512
    timeout: 30
  # iamRoleStatements:
  #   - Effect: "Allow"
  #     Action:
  #       - "sns:*"
  #       - "s3:*"
  #     Resource: "*"

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  service:
    handler: bin/service
    events:
      - http:
          path: /
          method: GET
      - http:
          path: /{path+}
          method: any

resources:
  Description: "Generic Sample Project - see github.com/aldrinleal/sls-go-template"
